package gov.iti.jets.clinify.models.entities;// default package
// Generated 16 Jun 2023, 19:10:03 by Hibernate Tools 6.1.7.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name="city"
    ,catalog="clinify"
)
public class City  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Patient> patients = new HashSet(0);
     private Set<Clinic> clinics = new HashSet(0);
     private Set<Area> areas = new HashSet(0);

    public City() {
    }

	
    public City(String name) {
        this.name = name;
    }
    public City(String name, Set<Patient> patients, Set<Clinic> clinics, Set<Area> areas) {
       this.name = name;
       this.patients = patients;
       this.clinics = clinics;
       this.areas = areas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="city")
    public Set<Patient> getPatients() {
        return this.patients;
    }
    
    public void setPatients(Set<Patient> patients) {
        this.patients = patients;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="city")
    public Set<Clinic> getClinics() {
        return this.clinics;
    }
    
    public void setClinics(Set<Clinic> clinics) {
        this.clinics = clinics;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="city")
    public Set<Area> getAreas() {
        return this.areas;
    }
    
    public void setAreas(Set<Area> areas) {
        this.areas = areas;
    }




}


