package gov.iti.jets.clinify.models.entities;// default package
// Generated 16 Jun 2023, 20:42:23 by Hibernate Tools 6.1.7.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name="doctor"
    ,catalog="clinify"
    , uniqueConstraints = @UniqueConstraint(columnNames="phone_number") 
)
public class Doctor extends BaseEntity {
     private DoctorTitle doctorTitle;
     private Clinic clinic;
     private DoctorSpecialization doctorSpecialization;
     private String fullName;
     private String phoneNumber;
     private int ticketPrice;
     private Double averageRating;
     private Integer ratingCount;
     private String status;
     private Boolean isDeleted;
    String imgUrl;


    private Integer avgMinutesPerPatient;
     private Set<Appointment> appointments = new HashSet(0);

    public Doctor() {
    }

	
    public Doctor(DoctorTitle doctorTitle, Clinic clinic, DoctorSpecialization doctorSpecialization, String fullName, String phoneNumber, int ticketPrice, Integer avgMinutesPerPatient) {
        this.doctorTitle = doctorTitle;
        this.clinic = clinic;
        this.doctorSpecialization = doctorSpecialization;
        this.fullName = fullName;
        this.phoneNumber = phoneNumber;
        this.ticketPrice = ticketPrice;
        this.avgMinutesPerPatient=avgMinutesPerPatient;
    }
    public Doctor(DoctorTitle doctorTitle, Clinic clinic, DoctorSpecialization doctorSpecialization, String fullName, String phoneNumber, int ticketPrice, Double averageRating, Integer ratingCount, String status, Boolean isDeleted, Set<Appointment> appointments) {
       this.doctorTitle = doctorTitle;
       this.clinic = clinic;
       this.doctorSpecialization = doctorSpecialization;
       this.fullName = fullName;
       this.phoneNumber = phoneNumber;
       this.ticketPrice = ticketPrice;
       this.averageRating = averageRating;
       this.ratingCount = ratingCount;
       this.status = status;
       this.isDeleted = isDeleted;
       this.appointments = appointments;
    }
   


@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="title_id", nullable=false)
    public DoctorTitle getDoctorTitle() {
        return this.doctorTitle;
    }
    
    public void setDoctorTitle(DoctorTitle doctorTitle) {
        this.doctorTitle = doctorTitle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="clinic_id", nullable=false)
    public Clinic getClinic() {
        return this.clinic;
    }
    
    public void setClinic(Clinic clinic) {
        this.clinic = clinic;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="specialization_id", nullable=false)
    public DoctorSpecialization getDoctorSpecialization() {
        return this.doctorSpecialization;
    }
    
    public void setDoctorSpecialization(DoctorSpecialization doctorSpecialization) {
        this.doctorSpecialization = doctorSpecialization;
    }

    
    @Column(name="full_name", nullable=false, length=200)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    
    @Column(name="phone_number", unique=true, nullable=false, length=11)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="ticket_price", nullable=false)
    public int getTicketPrice() {
        return this.ticketPrice;
    }
    
    public void setTicketPrice(int ticketPrice) {
        this.ticketPrice = ticketPrice;
    }

    
    @Column(name="average_rating", precision=22, scale=0)
    public Double getAverageRating() {
        return this.averageRating;
    }
    
    public void setAverageRating(Double averageRating) {
        this.averageRating = averageRating;
    }

    
    @Column(name="rating_count")
    public Integer getRatingCount() {
        return this.ratingCount;
    }
    
    public void setRatingCount(Integer ratingCount) {
        this.ratingCount = ratingCount;
    }

    
    @Column(name="status", length=8)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="is_deleted")
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Column(name="avg_minutes_per_patient")
    public Integer getAvgMinutesPerPatient() {
        return this.avgMinutesPerPatient;
    }

    public void setAvgMinutesPerPatient(Integer avgMinutesPerPatient) {
        this.avgMinutesPerPatient = avgMinutesPerPatient;
    }

    @Column(name="img_url")
    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="doctor")
    public Set<Appointment> getAppointments() {
        return this.appointments;
    }
    
    public void setAppointments(Set<Appointment> appointments) {
        this.appointments = appointments;
    }


    @Override
    public String toString() {
        return "Doctor{" +
                "doctorTitle=" + doctorTitle +
                ", clinic=" + clinic +
                ", doctorSpecialization=" + doctorSpecialization +
                ", fullName='" + fullName + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", ticketPrice=" + ticketPrice +
                ", averageRating=" + averageRating +
                ", ratingCount=" + ratingCount +
                ", status='" + status + '\'' +
                ", isDeleted=" + isDeleted +
                ", imgUrl='" + imgUrl + '\'' +
                ", avgMinutesPerPatient=" + avgMinutesPerPatient +
                ", appointments=" + appointments +
                '}';
    }
}


